[tool.black]
line-length = 99
target-version = ['py36', 'py37', 'py38']
exclude = '''
/(
    \.git
  | \.tox
  | \.venv
  | build
  | conf
  | contrib
  | data
  | docs
  | media
  | node_modules
  | shared-ci-files
  | static
  | tools
)/
'''

[tool.isort]
line_length = 99
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
force_single_line = true

known_future_library = ['future', '__future__']
known_first_party = ['kadoka', 'ciuvo', 'pyciuvo']
